language: python
sudo: false
python:
  - "2.7"
  - "3.4"
  - "3.5"

before_install:
  # Install miniconda
  # -----------------
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

  # Create the basic testing environment
  # ------------------------------------
  - conda config --set always_yes yes --set changeps1 no
  - conda config --set show_channel_urls True
  - conda config --add create_default_packages pip
  - conda update --quiet conda
  - ENV_NAME='test-environment'
  - conda create --quiet -n $ENV_NAME python=$TRAVIS_PYTHON_VERSION
  - source activate $ENV_NAME

install:
  # Customise the testing environment
  # ---------------------------------
  - conda install -c conda-forge --file requirements.txt
  - conda install -c conda-forge netCDF4  # For optional DAP file size calculation
  - conda install -c conda-forge pytest

script: py.test -rx -v

deploy:
  provider: releases
  api_key:
    secure: XAx2aeocMQWn2acXcQ5LevsO977glpvPKOnk/2yafHTMd+VROVy8jZjsVTTwOEhzag2xOYgTyDYbX5PRT2uG2Uz/RPwJA0PbB+9NIiT1gvHZ/sfFEm7AfOQ257I2IL72ZGUuSZoa0I1pZnIFaew84FZGQ/jsNtfWZzo1veXI6A0=
  on:
    tags: true
    repo: ioos/thredds_crawler
